### ISSUE TITLE
Doc improvements

### ISSUE THREAD

**Issue by ciphrd** [CyrianCrPro/nftai#1]
- [x] readme root should provide a short description and link to other sub-projects README
- [x] for every sub-project
  - [x] missing execution instructions (how to run the project)
  - [x] missing some extra research results (either with actual results we can inspect or some drawn conclusions)
  - [x] missing potential areas of improvement
  - [x] missing known caveats/limitations
  - [x] more generally, it might now be useful to document what each file is doing (which could be a comment at the top of the file itself), but rather explain general concepts (mainly included above) for understanding scope, purpose, how to replicate
  - [x] instructions to expand the dataset in a proper way
  - [x] system requirements ? (if known)
- [x] add `__pycache__` to gitignore and untrack `__pycache__` folders already committed: shouldn't be a part if the repo

**Comment by CyrianCrPro** [comment]
thanks! done
